### ISSUE TITLE
Unable to connect push api

### ISSUE THREAD

**Issue by bhavishyagoyal12** [TheCookieLab/poloniex-api-java#14]
I am unable to connect on websocket as suggested in example. Please help me what is wrong with me 

2017-07-20 09:54:52,429 main WARN No Root logger was configured, creating default ERROR-level Root logger with Console appender
09:54:58.527 [main] DEBUG io.netty.util.internal.logging.InternalLoggerFactory - Using SLF4J as the default logging framework
09:54:58.574 [main] DEBUG io.netty.handler.ssl.OpenSsl - netty-tcnative not in the classpath; OpenSslEngine will be unavailable.
09:55:00.737 [main] DEBUG io.netty.handler.ssl.JdkSslContext - Default protocols (JDK): [TLSv1.2, TLSv1.1, TLSv1] 
09:55:00.743 [main] DEBUG io.netty.handler.ssl.JdkSslContext - Default cipher suites (JDK): [TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA, TLS_RSA_WITH_AES_128_GCM_SHA256, TLS_RSA_WITH_AES_128_CBC_SHA]
09:55:00.803 [main] DEBUG io.netty.util.internal.PlatformDependent0 - -Dio.netty.noUnsafe: false
09:55:00.807 [main] DEBUG io.netty.util.internal.PlatformDependent0 - sun.misc.Unsafe.theUnsafe: available
09:55:00.809 [main] DEBUG io.netty.util.internal.PlatformDependent0 - sun.misc.Unsafe.copyMemory: available
09:55:00.811 [main] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.Buffer.address: available
09:55:00.813 [main] DEBUG io.netty.util.internal.PlatformDependent0 - direct buffer constructor: available
09:55:00.815 [main] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.Bits.unaligned: available, true
09:55:00.824 [main] DEBUG io.netty.util.internal.PlatformDependent0 - jdk.internal.misc.Unsafe.allocateUninitializedArray(int): unavailable
java.lang.ClassNotFoundException: jdk.internal.misc.Unsafe
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at io.netty.util.internal.PlatformDependent0$6.run(PlatformDependent0.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at io.netty.util.internal.PlatformDependent0.<clinit>(PlatformDependent0.java:288)
	at io.netty.util.internal.PlatformDependent.getSystemClassLoader(PlatformDependent.java:895)
	at io.netty.util.internal.PlatformDependent.isAndroid0(PlatformDependent.java:919)
	at io.netty.util.internal.PlatformDependent.<clinit>(PlatformDependent.java:70)
	at io.netty.handler.ssl.util.SimpleTrustManagerFactory$SimpleTrustManagerFactorySpi.engineGetTrustManagers(SimpleTrustManagerFactory.java:138)
	at javax.net.ssl.TrustManagerFactory.getTrustManagers(TrustManagerFactory.java:285)
	at io.netty.handler.ssl.JdkSslClientContext.newSSLContext(JdkSslClientContext.java:290)
	at io.netty.handler.ssl.JdkSslClientContext.<init>(JdkSslClientContext.java:270)
	at io.netty.handler.ssl.SslContext.newClientContextInternal(SslContext.java:770)
	at io.netty.handler.ssl.SslContextBuilder.build(SslContextBuilder.java:446)
	at ws.wamp.jawampa.transport.netty.NettyWampClientConnectorProvider.createConnector(NettyWampClientConnectorProvider.java:113)
	at ws.wamp.jawampa.WampClientBuilder.build(WampClientBuilder.java:127)
	at com.cf.client.WSSClient.<init>(WSSClient.java:38)
	at com.hftsolution.service.PoloniexService.init(PoloniexService.java:33)
	at com.hftsolution.service.PoloniexServiceTest.init(PoloniexServiceTest.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
09:55:00.826 [main] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.DirectByteBuffer.<init>(long, int): available
09:55:00.829 [main] DEBUG io.netty.util.internal.PlatformDependent - Platform: Windows
09:55:00.829 [main] DEBUG io.netty.util.internal.PlatformDependent - Java version: 8
09:55:00.829 [main] DEBUG io.netty.util.internal.PlatformDependent - sun.misc.Unsafe: available
09:55:00.830 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.tmpdir: C:\Users\bhavi\AppData\Local\Temp (java.io.tmpdir)
09:55:00.830 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.bitMode: 64 (sun.arch.data.model)
09:55:00.842 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.noPreferDirect: false
09:55:00.842 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.maxDirectMemory: 1884815360 bytes
09:55:00.843 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.uninitializedArrayAllocationThreshold: -1
09:55:00.845 [main] DEBUG io.netty.util.internal.CleanerJava6 - java.nio.ByteBuffer.cleaner(): available
09:55:01.021 [main] DEBUG io.netty.channel.MultithreadEventLoopGroup - -Dio.netty.eventLoopThreads: 8
09:55:01.099 [main] DEBUG io.netty.channel.nio.NioEventLoop - -Dio.netty.noKeySetOptimization: false
09:55:01.100 [main] DEBUG io.netty.channel.nio.NioEventLoop - -Dio.netty.selectorAutoRebuildThreshold: 512
09:55:01.108 [main] DEBUG io.netty.util.internal.PlatformDependent - org.jctools-core.MpscChunkedArrayQueue: available
2017-07-20 09:55:39,075 [main] TRACE WSSClient - Disconnected
2017-07-20 09:56:15,195 [WampClientEventLoop] TRACE WSSClient - Connecting...
09:56:15.433 [WampClientEventLoop] DEBUG io.netty.channel.DefaultChannelId - -Dio.netty.processId: 2036 (auto-detected)
09:56:15.444 [WampClientEventLoop] DEBUG io.netty.util.NetUtil - -Djava.net.preferIPv4Stack: false
09:56:15.445 [WampClientEventLoop] DEBUG io.netty.util.NetUtil - -Djava.net.preferIPv6Addresses: false
09:56:15.550 [WampClientEventLoop] DEBUG io.netty.util.NetUtil - Loopback interface: lo (Software Loopback Interface 1, 127.0.0.1)
09:56:15.553 [WampClientEventLoop] DEBUG io.netty.util.NetUtil - Failed to get SOMAXCONN from sysctl and file \proc\sys\net\core\somaxconn. Default: 200
09:56:15.693 [WampClientEventLoop] DEBUG io.netty.channel.DefaultChannelId - -Dio.netty.machineId: 00:00:00:00:00:00:00:e0 (auto-detected)
09:56:15.780 [WampClientEventLoop] DEBUG io.netty.util.ResourceLeakDetector - -Dio.netty.leakDetection.level: simple
09:56:15.780 [WampClientEventLoop] DEBUG io.netty.util.ResourceLeakDetector - -Dio.netty.leakDetection.maxRecords: 4
09:56:15.824 [WampClientEventLoop] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.numHeapArenas: 8
09:56:15.825 [WampClientEventLoop] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.numDirectArenas: 8
09:56:15.825 [WampClientEventLoop] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.pageSize: 8192
09:56:15.827 [WampClientEventLoop] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.maxOrder: 11
09:56:15.827 [WampClientEventLoop] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.chunkSize: 16777216
09:56:15.827 [WampClientEventLoop] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.tinyCacheSize: 512
09:56:15.827 [WampClientEventLoop] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.smallCacheSize: 256
09:56:15.827 [WampClientEventLoop] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.normalCacheSize: 64
09:56:15.827 [WampClientEventLoop] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.maxCachedBufferCapacity: 32768
09:56:15.827 [WampClientEventLoop] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.cacheTrimInterval: 8192
09:56:15.827 [WampClientEventLoop] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.useCacheForAllThreads: true
09:56:15.844 [WampClientEventLoop] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.allocator.type: pooled
09:56:15.845 [WampClientEventLoop] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.threadLocalDirectBufferSize: 65536
09:56:15.845 [WampClientEventLoop] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.maxThreadLocalCharBufferSize: 16384
09:56:15.935 [WampClientEventLoop] DEBUG io.netty.buffer.AbstractByteBuf - -Dio.netty.buffer.bytebuf.checkAccessible: true
09:56:15.937 [WampClientEventLoop] DEBUG io.netty.util.ResourceLeakDetectorFactory - Loaded default ResourceLeakDetector: io.netty.util.ResourceLeakDetector@44f32d7f
09:56:16.107 [WampClientEventLoop] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.maxCapacityPerThread: 32768
09:56:16.107 [WampClientEventLoop] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.maxSharedCapacityFactor: 2
09:56:16.107 [WampClientEventLoop] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.linkCapacity: 16
09:56:16.107 [WampClientEventLoop] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.ratio: 8
09:56:16.136 [WampClientEventLoop] DEBUG io.netty.handler.codec.http.websocketx.WebSocketClientHandshaker13 - WebSocket version 13 client handshake key: YYh4WqOvs+KE6/u3Fu8syg==, expected response: Wlw4buO93JCWcEY/PYKDyf+4ugI=
09:56:16.204 [WampClientEventLoop] DEBUG io.netty.handler.ssl.util.InsecureTrustManagerFactory - Accepting a server certificate: CN=*.poloniex.com, OU=Domain Control Validated
09:56:16.398 [WampClientEventLoop] DEBUG io.netty.handler.ssl.SslHandler - [id: 0xc0efd083, L:/192.168.1.7:64473 - R:api.poloniex.com/104.20.12.48:443] HANDSHAKEN: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256

**Comment by TheCookieLab** [comment]
https://github.com/netty/netty/issues/6855

I would recommend you open an issue in the Jawampa Github and encourage them to upgrade their Netty library to 4.1.12. Alternatively, you can fork and build your own Jawampa library and use the latest Netty version.

**Comment by TheCookieLab** [comment]
Try pulling the latest master code. I've overridden the Jawampa netty libraries and using the latest 4.1.12.FINAL now.
