### ISSUE TITLE
java.lang.NoClassDefFoundError when trying to use any PoloniexExchangeService method

### ISSUE THREAD

**Issue by welsh01** [TheCookieLab/poloniex-api-java#36]
After initiating a _PolononiexExchangeService_ (with or without api keypair), i get this error when trying to call any method (like _returnAllMarkets()_):

`Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/logging/log4j/message/ParameterVisitable
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:801)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:699)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:622)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:580)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at org.apache.logging.log4j.core.impl.ReusableLogEventFactory.createEvent(ReusableLogEventFactory.java:63)
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:404)
	at org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:63)
	at org.apache.logging.log4j.core.Logger.logMessage(Logger.java:146)
	at org.apache.logging.log4j.spi.AbstractLogger.tryLogMessage(AbstractLogger.java:2116)
	at org.apache.logging.log4j.spi.AbstractLogger.logMessageSafely(AbstractLogger.java:2100)
	at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:2011)
	at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1882)
	at org.apache.logging.log4j.spi.AbstractLogger.trace(AbstractLogger.java:2372)
	at com.cf.client.poloniex.PoloniexExchangeService.returnAllMarkets(PoloniexExchangeService.java:126)
	at exchanges.poloniex.MarketDataPoloniex.main(MarketDataPoloniex.java:16)
Caused by: java.lang.ClassNotFoundException: org.apache.logging.log4j.message.ParameterVisitable
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 20 more`

**Comment by TheCookieLab** [comment]
Did you exclude any of the dependencies?

**Comment by welsh01** [comment]
Hello CookieLab!
Oh, man, it was indeed following dependency, i had to add to my pom.xml:

`<dependency>`
            
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-core</artifactId>
            <version>2.9.1</version>
`</dependency>`

Intellij does not seem to use that Log4J version by default. 

Thank you!
